const countries = {
    GH: {engName: 'Ghana', korName: '가나', flag: '🇬🇭'},
    GA: {engName: 'Gabon', korName: '가봉', flag: '🇬🇦'},
    GY: {engName: 'Guyana', korName: '가이아나', flag: '🇬🇾'},
    GM: {engName: 'Gambia', korName: '감비아', flag: '🇬🇲'},
    GG: {engName: 'Guernsey', korName: '건지 섬', flag: '🇬🇬'},
    GP: {engName: 'Guadeloupe', korName: '과들루프', flag: '🇬🇵'},
    GT: {engName: 'Guatemala', korName: '과테말라', flag: '🇬🇹'},
    GU: {engName: 'Guam', korName: '괌', flag: '🇬🇺'},
    GD: {engName: 'Grenada', korName: '그레나다', flag: '🇬🇩'},
    GE: {engName: 'Georgia', korName: '조지아', flag: '🇬🇪'},
    GR: {engName: 'Greece', korName: '그리스', flag: '🇬🇷'},
    GL: {engName: 'Greenland', korName: '그린란드', flag: '🇬🇱'},
    GN: {engName: 'Guinea', korName: '기니', flag: '🇬🇳'},
    GW: {engName: 'Guinea-Bissau', korName: '기니비사우', flag: '🇬🇼'},
    NA: {engName: 'Namibia', korName: '나미비아', flag: '🇳🇦'},
    NR: {engName: 'Nauru', korName: '나우루', flag: '🇳🇷'},
    NG: {engName: 'Nigeria', korName: '나이지리아', flag: '🇳🇬'},
    AQ: {engName: 'Antarctica', korName: '남극', flag: '🇦🇶'},
    ZA: {engName: 'South Africa', korName: '남아프리카 공화국', flag: '🇿🇦'},
    NL: {engName: 'Netherlands', korName: '네덜란드', flag: '🇳🇱'},
    AN: {engName: 'Netherlands Antilles', korName: '네덜란드령 안틸레스', flag: '🇳🇱'},
    NP: {engName: 'Nepal', korName: '네팔', flag: '🇳🇵'},
    NO: {engName: 'Norway', korName: '노르웨이', flag: '🇳🇴'},
    NF: {engName: 'Norfolk Island', korName: '노퍽 섬', flag: '🇳🇫'},
    NC: {engName: 'New Caledonia', korName: '누벨칼레도니', flag: '🇳🇨'},
    NZ: {engName: 'New Zealand', korName: '뉴질랜드', flag: '🇳🇿'},
    NU: {engName: 'Niue', korName: '니우에', flag: '🇳🇺'},
    NE: {engName: 'Niger', korName: '니제르', flag: '🇳🇪'},
    NI: {engName: 'Nicaragua', korName: '니카라과', flag: '🇳🇮'},
    KR: {engName: 'South Korea', korName: '대한민국', flag: '🇰🇷'},
    DK: {engName: 'Denmark', korName: '덴마크', flag: '🇩🇰'},
    DM: {engName: 'Dominica', korName: '도미니카', flag: '🇩🇲'},
    DO: {engName: 'Dominican Republic', korName: '도미니카 공화국', flag: '🇨🇩'},
    DE: {engName: 'Germany', korName: '독일', flag: '🇩🇪'},
    TL: {engName: 'Timor-Leste', korName: '동티모르', flag: '🇹🇱'},
    LA: {engName: 'Laos', korName: '라오스', flag: '🇱🇦'},
    LR: {engName: 'Liberia', korName: '라이베리아', flag: '🇱🇷'},
    LV: {engName: 'Latvia', korName: '라트비아', flag: '🇱🇻'},
    RU: {engName: 'Russia', korName: '러시아', flag: '🇷🇺'},
    LB: {engName: 'Lebanon', korName: '레바논', flag: '🇱🇧'},
    LS: {engName: 'Lesotho', korName: '레소토', flag: '🇱🇸'},
    RE: {engName: 'Reunion', korName: '레위니옹', flag: '🇫🇷'},
    RO: {engName: 'Romania', korName: '루마니아', flag: '🇷🇴'},
    LU: {engName: 'Luxembourg', korName: '룩셈부르크', flag: '🇱🇺'},
    RW: {engName: 'Rwanda', korName: '르완다', flag: '🇷🇼'},
    LY: {engName: 'Libyan Arab Jamahiriya', korName: '리비아', flag: '🇱🇾'},
    LT: {engName: 'Lithuania', korName: '리투아니아', flag: '🇱🇹'},
    LI: {engName: 'Liechtenstein', korName: '리히텐슈타인', flag: '🇱🇮'},
    MG: {engName: 'Madagascar', korName: '마다가스카르', flag: '🇲🇬'},
    MQ: {engName: 'Martinique', korName: '마르티니크', flag: '🇲🇶'},
    MH: {engName: 'Marshall Islands', korName: '마셜 제도', flag: '🇲🇭'},
    YT: {engName: 'Mayotte', korName: '마요트', flag: '🇾🇹'},
    MO: {engName: 'Macao', korName: '마카오', flag: '🇲🇴'},
    MK: {engName: 'Macedonia', korName: '마케도니아 공화국', flag: '🇲🇰'},
    MW: {engName: 'Malawi', korName: '말라위', flag: '🇲🇼'},
    MY: {engName: 'Malaysia', korName: '말레이시아', flag: '🇲🇾'},
    ML: {engName: 'Mali', korName: '말리', flag: '🇲🇱'},
    IM: {engName: 'Isle of Man', korName: '맨 섬', flag: '🇮🇲'},
    MX: {engName: 'Mexico', korName: '멕시코', flag: '🇲🇽'},
    MC: {engName: 'Monaco', korName: '모나코', flag: '🇲🇨'},
    MA: {engName: 'Morocco', korName: '모로코', flag: '🇲🇦'},
    MU: {engName: 'Mauritius', korName: '모리셔스', flag: '🇲🇺'},
    MR: {engName: 'Mauritania', korName: '모리타니', flag: '🇲🇷'},
    MZ: {engName: 'Mozambique', korName: '모잠비크', flag: '🇲🇿'},
    ME: {engName: 'Montenegro', korName: '몬테네그로', flag: '🇲🇪'},
    MS: {engName: 'Montserrat', korName: '몬트세랫', flag: '🇲🇸'},
    MD: {engName: 'Moldova', korName: '몰도바', flag: '🇲🇩'},
    MV: {engName: 'Maldives', korName: '몰디브', flag: '🇲🇻'},
    MT: {engName: 'Malta', korName: '몰타', flag: '🇲🇹'},
    MN: {engName: 'Mongolia', korName: '몽골', flag: '🇲🇳'},
    US: {engName: 'United States', korName: '미국', flag: '🇺🇸'},
    UM: {engName: 'United States Minor Outlying Islands', korName: '미국령 군소 제도', flag: '🇺🇸'},
    VI: {engName: 'Virgin Islands, U.S.', korName: '미국령 버진아일랜드', flag: '🇻🇮'},
    MM: {engName: 'Myanmar', korName: '미얀마', flag: '🇲🇲'},
    FM: {engName: 'Micronesia', korName: '미크로네시아 연방', flag: '🇫🇲'},
    VU: {engName: 'Vanuatu', korName: '바누아투', flag: '🇻🇺'},
    BH: {engName: 'Bahrain', korName: '바레인', flag: '🇧🇸'},
    BB: {engName: 'Barbados', korName: '바베이도스', flag: '🇧🇧'},
    VA: {engName: 'Holy See', korName: '바티칸 시국', flag: '🇻🇦'},
    BS: {engName: 'Bahamas', korName: '바하마', flag: '🇧🇸'},
    BD: {engName: 'Bangladesh', korName: '방글라데시', flag: '🇧🇩'},
    BM: {engName: 'Bermuda', korName: '버뮤다', flag: '🇧🇲'},
    BJ: {engName: 'Benin', korName: '베냉', flag: '🇧🇯'},
    VE: {engName: 'Venezuela', korName: '베네수엘라', flag: '🇻🇪'},
    VN: {engName: 'Vietnam', korName: '베트남', flag: '🇻🇳'},
    BE: {engName: 'Belgium', korName: '벨기에', flag: '🇧🇪'},
    BY: {engName: 'Belarus', korName: '벨라루스', flag: '🇧🇾'},
    BZ: {engName: 'Belize', korName: '벨리즈', flag: '🇧🇿'},
    BA: {engName: 'Bosnia and Herzegovina', korName: '보스니아 헤르체고비나', flag: '🇧🇦'},
    BW: {engName: 'Botswana', korName: '보츠와나', flag: '🇧🇼'},
    BO: {engName: 'Bolivia', korName: '볼리비아', flag: '🇧🇴'},
    BI: {engName: 'Burundi', korName: '부룬디', flag: '🇧🇮'},
    BF: {engName: 'Burkina Faso', korName: '부르키나파소', flag: '🇧🇫'},
    BV: {engName: 'Bouvet Island', korName: '부베 섬', flag: '🏳'},
    BT: {engName: 'Bhutan', korName: '부탄', flag: '🇧🇹'},
    MP: {engName: 'Northern Mariana Islands', korName: '북마리아나 제도', flag: '🏳'},
    BG: {engName: 'Bulgaria', korName: '불가리아', flag: '🇧🇬'},
    BR: {engName: 'Brazil', korName: '브라질', flag: '🇧🇷'},
    BN: {engName: 'Brunei Darussalam', korName: '브루나이', flag: '🇧🇳'},
    WS: {engName: 'Samoa', korName: '사모아', flag: '🇼🇸'},
    SA: {engName: 'Saudi Arabia', korName: '사우디아라비아', flag: '🇸🇦'},
    GS: {engName: 'South Georgia', korName: '사우스조지아 사우스샌드위치 제도', flag: '🇬🇸'},
    SM: {engName: 'San Marino', korName: '산마리노', flag: '🇸🇲'},
    ST: {engName: 'Sao Tome and Principe', korName: '상투메 프린시페', flag: '🇸🇹'},
    PM: {engName: 'Saint Pierre and Miquelon', korName: '생피에르 미클롱', flag: '🇵🇲'},
    EH: {engName: 'Western Sahara', korName: '서사하라', flag: '🇪🇭'},
    SN: {engName: 'Senegal', korName: '세네갈', flag: '🇸🇳'},
    RS: {engName: 'Serbia', korName: '세르비아', flag: '🇷🇸'},
    SC: {engName: 'Seychelles', korName: '세이셸', flag: '🇸🇨'},
    LC: {engName: 'Saint Lucia', korName: '세인트루시아', flag: '🇱🇨'},
    VC: {engName: 'Saint Vincent and the Grenadines', korName: '세인트빈센트 그레나딘', flag: '🇻🇨'},
    KN: {engName: 'Saint Kitts and Nevis', korName: '세인트키츠 네비스', flag: '🇰🇳'},
    SH: {engName: 'Saint Helena', korName: '세인트헬레나', flag: '🇸🇭'},
    SO: {engName: 'Somalia', korName: '소말리아', flag: '🇸🇴'},
    SB: {engName: 'Solomon Islands', korName: '솔로몬 제도', flag: '🇸🇧'},
    SD: {engName: 'Sudan', korName: '수단', flag: '🇸🇩'},
    SR: {engName: 'Suriname', korName: '수리남', flag: '🇸🇷'},
    LK: {engName: 'Sri Lanka', korName: '스리랑카', flag: '🇱🇰'},
    SJ: {engName: 'Svalbard and Jan Mayen', korName: '스발바르 얀마옌', flag: '🇩🇰'},
    SZ: {engName: 'Swaziland', korName: '스와질란드', flag: '🇸🇿'},
    SE: {engName: 'Sweden', korName: '스웨덴', flag: '🇸🇪'},
    CH: {engName: 'Switzerland', korName: '스위스', flag: '🇨🇭'},
    ES: {engName: 'Spain', korName: '스페인', flag: '🇪🇸'},
    SK: {engName: 'Slovakia', korName: '슬로바키아', flag: '🇸🇰'},
    SI: {engName: 'Slovenia', korName: '슬로베니아', flag: '🇸🇮'},
    SY: {engName: 'Syrian Arab Republic', korName: '시리아', flag: '🇸🇾'},
    SL: {engName: 'Sierra Leone', korName: '시에라리온', flag: '🇸🇱'},
    SG: {engName: 'Singapore', korName: '싱가포르', flag: '🇸🇬'},
    AE: {engName: 'United Arab Emirates', korName: '아랍에미리트', flag: '🇦🇪'},
    AW: {engName: 'Aruba', korName: '아루바', flag: '🇦🇼'},
    AM: {engName: 'Armenia', korName: '아르메니아', flag: '🇦🇲'},
    AR: {engName: 'Argentina', korName: '아르헨티나', flag: '🇦🇷'},
    AS: {engName: 'American Samoa', korName: '아메리칸사모아', flag: '🇺🇸'},
    IS: {engName: 'Iceland', korName: '아이슬란드', flag: '🇮🇸'},
    HT: {engName: 'Haiti', korName: '아이티', flag: '🇭🇹'},
    IE: {engName: 'Ireland', korName: '아일랜드', flag: '🇮🇪'},
    AZ: {engName: 'Azerbaijan', korName: '아제르바이잔', flag: '🇦🇿'},
    AF: {engName: 'Afghanistan', korName: '아프가니스탄', flag: '🇦🇫'},
    AD: {engName: 'Andorra', korName: '안도라', flag: '🇦🇩'},
    AL: {engName: 'Albania', korName: '알바니아', flag: '🇦🇱'},
    DZ: {engName: 'Algeria', korName: '알제리', flag: '🇩🇿'},
    AO: {engName: 'Angola', korName: '앙골라', flag: '🇦🇴'},
    AG: {engName: 'Antigua and Barbuda', korName: '앤티가 바부다', flag: '🇦🇬'},
    AI: {engName: 'Anguilla', korName: '앵귈라', flag: '🇦🇮'},
    ER: {engName: 'Eritrea', korName: '에리트레아', flag: '🇪🇷'},
    EE: {engName: 'Estonia', korName: '에스토니아', flag: '🇪🇪'},
    EC: {engName: 'Ecuador', korName: '에콰도르', flag: '🇪🇨'},
    ET: {engName: 'Ethiopia', korName: '에티오피아', flag: '🇪🇹'},
    SV: {engName: 'El Salvador', korName: '엘살바도르', flag: '🇸🇻'},
    GB: {engName: 'United Kingdom', korName: '영국', flag: '🇬🇧'},
    VG: {engName: 'Virgin Islands, British', korName: '영국령 버진아일랜드', flag: '🇻🇬'},
    IO: {engName: 'British Indian Ocean Territory', korName: '영국령 인도양 지역', flag: '🇮🇴'},
    YE: {engName: 'Yemen', korName: '예멘', flag: '🇾🇪'},
    OM: {engName: 'Oman', korName: '오만', flag: '🇴🇲'},
    AU: {engName: 'Australia', korName: '오스트레일리아', flag: '🇦🇺'},
    AT: {engName: 'Austria', korName: '오스트리아', flag: '🇦🇹'},
    HN: {engName: 'Honduras', korName: '온두라스', flag: '🇭🇳'},
    AX: {engName: 'Åland Islands', korName: '올란드 제도', flag: '🇦🇽'},
    JO: {engName: 'Jordan', korName: '요르단', flag: '🇯🇴'},
    UG: {engName: 'Uganda', korName: '우간다', flag: '🇺🇬'},
    UY: {engName: 'Uruguay', korName: '우루과이', flag: '🇺🇾'},
    UZ: {engName: 'Uzbekistan', korName: '우즈베키스탄', flag: '🇺🇿'},
    UA: {engName: 'Ukraine', korName: '우크라이나', flag: '🇺🇦'},
    WF: {engName: 'Wallis and Futuna', korName: '왈리스 퓌튀나', flag: '🇼🇫'},
    IQ: {engName: 'Iraq', korName: '이라크', flag: '🇮🇶'},
    IR: {engName: 'Iran', korName: '이란', flag: '🇮🇷'},
    IL: {engName: 'Israel', korName: '이스라엘', flag: '🇮🇱'},
    EG: {engName: 'Egypt', korName: '이집트', flag: '🇪🇬'},
    IT: {engName: 'Italy', korName: '이탈리아', flag: '🇮🇹'},
    ID: {engName: 'Indonesia', korName: '인도네시아', flag: '🇮🇩'},
    IN: {engName: 'India', korName: '인도', flag: '🇮🇳'},
    JP: {engName: 'Japan', korName: '일본', flag: '🇯🇵'},
    JM: {engName: 'Jamaica', korName: '자메이카', flag: '🇯🇲'},
    ZM: {engName: 'Zambia', korName: '잠비아', flag: '🇿🇲'},
    JE: {engName: 'Jersey', korName: '저지 섬', flag: '🇯🇪'},
    GQ: {engName: 'Equatorial Guinea', korName: '적도 기니', flag: '🇬🇶'},
    KP: {engName: 'North Korea', korName: '조선민주주의인민공화국', flag: '🇰🇵'},
    CF: {engName: 'Central African Republic', korName: '중앙아프리카 공화국', flag: '🇨🇫'},
    TW: {engName: 'Taiwan', korName: '중화민국', flag: '🇹🇼'},
    CN: {engName: 'China', korName: '중화인민공화국', flag: '🇨🇳'},
    DJ: {engName: 'Djibouti', korName: '지부티', flag: '🇩🇯'},
    GI: {engName: 'Gibraltar', korName: '지브롤터', flag: '🇬🇮'},
    ZW: {engName: 'Zimbabwe', korName: '짐바브웨', flag: '🇿🇼'},
    TD: {engName: 'Chad', korName: '차드', flag: '🇹🇩'},
    CZ: {engName: 'Czech Republic', korName: '체코', flag: '🇨🇿'},
    CL: {engName: 'Chile', korName: '칠레', flag: '🇨🇱'},
    CM: {engName: 'Cameroon', korName: '카메룬', flag: '🇨🇲'},
    CV: {engName: 'Cape Verde', korName: '카보베르데', flag: '🇨🇻'},
    KZ: {engName: 'Kazakhstan', korName: '카자흐스탄', flag: '🇰🇿'},
    QA: {engName: 'Qatar', korName: '카타르', flag: '🇶🇦'},
    KH: {engName: 'Cambodia', korName: '캄보디아', flag: '🇰🇭'},
    CA: {engName: 'Canada', korName: '캐나다', flag: '🇨🇦'},
    KE: {engName: 'Kenya', korName: '케냐', flag: '🇰🇪'},
    KY: {engName: 'Cayman Islands', korName: '케이맨 제도', flag: '🇰🇾'},
    KM: {engName: 'Comoros', korName: '코모로', flag: '🇰🇲'},
    CR: {engName: 'Costa Rica', korName: '코스타리카', flag: '🇨🇷'},
    CC: {engName: 'Cocos (Keeling) Islands', korName: '코코스 제도', flag: '🇨🇨'},
    CI: {engName: "Cote d'Ivoire", korName: '코트디부아르', flag: '🇨🇮'},
    CO: {engName: 'Colombia', korName: '콜롬비아', flag: '🇨🇴'},
    CG: {engName: 'Congo', korName: '콩고 공화국', flag: '🇨🇬'},
    CD: {engName: 'Congo, The Democratic Republic of the Congo', korName: '콩고 민주 공화국', flag: '🇨🇩'},
    CU: {engName: 'Cuba', korName: '쿠바', flag: '🇨🇺'},
    KW: {engName: 'Kuwait', korName: '쿠웨이트', flag: '🇰🇼'},
    CK: {engName: 'Cook Islands', korName: '쿡 제도', flag: '🇨🇰'},
    HR: {engName: 'Croatia', korName: '크로아티아', flag: '🇭🇷'},
    CX: {engName: 'Christmas Island', korName: '크리스마스 섬', flag: '🇨🇽'},
    KG: {engName: 'Kyrgyzstan', korName: '키르기스스탄', flag: '🇰🇬'},
    KI: {engName: 'Kiribati', korName: '키리바시', flag: '🇰🇮'},
    CY: {engName: 'Cyprus', korName: '키프로스', flag: '🇨🇾'},
    TH: {engName: 'Thailand', korName: '타이', flag: '🇹🇭'},
    TJ: {engName: 'Tajikistan', korName: '타지키스탄', flag: '🇹🇯'},
    TZ: {engName: 'Tanzania', korName: '탄자니아', flag: '🇹🇿'},
    TC: {engName: 'Turks and Caicos Islands', korName: '터크스 케이커스 제도', flag: '🇹🇨'},
    TR: {engName: 'Turkey', korName: '터키', flag: '🇹🇷'},
    TG: {engName: 'Togo', korName: '토고', flag: '🇹🇬'},
    TK: {engName: 'Tokelau', korName: '토켈라우', flag: '🇹🇰'},
    TO: {engName: 'Tonga', korName: '통가', flag: '🇹🇴'},
    TM: {engName: 'Turkmenistan', korName: '투르크메니스탄', flag: '🇹🇲'},
    TV: {engName: 'Tuvalu', korName: '투발루', flag: '🇹🇻'},
    TN: {engName: 'Tunisia', korName: '튀니지', flag: '🇹🇳'},
    TT: {engName: 'Trinidad and Tobago', korName: '트리니다드 토바고', flag: '🇹🇹'},
    PA: {engName: 'Panama', korName: '파나마', flag: '🇵🇦'},
    PY: {engName: 'Paraguay', korName: '파라과이', flag: '🇵🇾'},
    PK: {engName: 'Pakistan', korName: '파키스탄', flag: '🇵🇰'},
    PG: {engName: 'Papua New Guinea', korName: '파푸아 뉴기니', flag: '🇵🇬'},
    PW: {engName: 'Palau', korName: '팔라우', flag: '🇵🇼'},
    PS: {engName: 'Palestinian Territory', korName: '팔레스타인', flag: '🇵🇸'},
    FO: {engName: 'Faroe Islands', korName: '페로 제도', flag: '🇫🇴'},
    PE: {engName: 'Peru', korName: '페루', flag: '🇵🇪'},
    PT: {engName: 'Portugal', korName: '포르투갈', flag: '🇵🇹'},
    FK: {engName: 'Falkland Islands', korName: '포클랜드 제도', flag: '🇫🇰'},
    PL: {engName: 'Poland', korName: '폴란드', flag: '🇵🇱'},
    PR: {engName: 'Puerto Rico', korName: '푸에르토리코', flag: '🇵🇷'},
    FR: {engName: 'France', korName: '프랑스', flag: '🇫🇷'},
    GF: {engName: 'French Guiana', korName: '프랑스령 기아나', flag: '🇬🇫'},
    TF: {engName: 'French Southern Territories', korName: '프랑스령 남부와 남극 지역', flag: '🇹🇫'},
    PF: {engName: 'French Polynesia', korName: '프랑스령 폴리네시아', flag: '🇵🇫'},
    FJ: {engName: 'Fiji', korName: '피지', flag: '🇫🇯'},
    FI: {engName: 'Finland', korName: '핀란드', flag: '🇫🇮'},
    PH: {engName: 'Philippines', korName: '필리핀', flag: '🇵🇭'},
    PN: {engName: 'Pitcairn', korName: '핏케언 제도', flag: '🇵🇳'},
    HM: {engName: 'Heard Island and Mcdonald Islands', korName: '허드 맥도널드 제도', flag: '🏳'},
    HU: {engName: 'Hungary', korName: '헝가리', flag: '🇭🇺'},
    HK: {engName: 'Hong Kong', korName: '홍콩', flag: '🇭🇰'},
};

export default countries;
