export const countries = [
    {flag: '🇬🇭', code: 'GH', currency: 'GHS', engName: 'Ghana', korName: '가나'},
    {flag: '🇬🇦', code: 'GA', currency: 'XAF', engName: 'Gabon', korName: '가봉'},
    {flag: '🇬🇾', code: 'GY', currency: 'GYD', engName: 'Guyana', korName: '가이아나'},
    {flag: '🇬🇲', code: 'GM', currency: 'GMD', engName: 'Gambia', korName: '감비아'},
    {flag: '🇬🇬', code: 'GG', currency: 'GBP', engName: 'Guernsey', korName: '건지 섬'},
    {flag: '🇬🇵', code: 'GP', currency: 'EUR', engName: 'Guadeloupe', korName: '과들루프'},
    {flag: '🇬🇹', code: 'GT', currency: 'GTQ', engName: 'Guatemala', korName: '과테말라'},
    {flag: '🇬🇺', code: 'GU', currency: 'USD', engName: 'Guam', korName: '괌'},
    {flag: '🇬🇩', code: 'GD', currency: 'XCD', engName: 'Grenada', korName: '그레나다'},
    {flag: '🇬🇪', code: 'GE', currency: 'GEL', engName: 'Georgia', korName: '조지아'},
    {flag: '🇬🇷', code: 'GR', currency: 'EUR', engName: 'Greece', korName: '그리스'},
    {flag: '🇬🇱', code: 'GL', currency: 'DKK', engName: 'Greenland', korName: '그린란드'},
    {flag: '🇬🇳', code: 'GN', currency: 'GNF', engName: 'Guinea', korName: '기니'},
    {flag: '🇬🇼', code: 'GW', currency: 'XOF', engName: 'Guinea-Bissau', korName: '기니비사우'},
    {flag: '🇳🇦', code: 'NA', currency: 'NAD', engName: 'Namibia', korName: '나미비아'},
    {flag: '🇳🇷', code: 'NR', currency: 'AUD', engName: 'Nauru', korName: '나우루'},
    {flag: '🇳🇬', code: 'NG', currency: 'NGN', engName: 'Nigeria', korName: '나이지리아'},
    {flag: '🇿🇦', code: 'ZA', currency: 'ZAR', engName: 'South Africa', korName: '남아프리카 공화국'},
    {flag: '🇳🇱', code: 'NL', currency: 'EUR', engName: 'Netherlands', korName: '네덜란드'},
    {flag: '🇳🇵', code: 'NP', currency: 'NPR', engName: 'Nepal', korName: '네팔'},
    {flag: '🇳🇴', code: 'NO', currency: 'NOK', engName: 'Norway', korName: '노르웨이'},
    {flag: '🇳🇫', code: 'NF', currency: 'AUD', engName: 'Norfolk Island', korName: '노퍽 섬'},
    {flag: '🇳🇨', code: 'NC', currency: 'XPF', engName: 'New Caledonia', korName: '누벨칼레도니'},
    {flag: '🇳🇿', code: 'NZ', currency: 'NZD', engName: 'New Zealand', korName: '뉴질랜드'},
    {flag: '🇳🇺', code: 'NU', currency: 'NZD', engName: 'Niue', korName: '니우에'},
    {flag: '🇳🇪', code: 'NE', currency: 'XOF', engName: 'Niger', korName: '니제르'},
    {flag: '🇳🇮', code: 'NI', currency: 'NIO', engName: 'Nicaragua', korName: '니카라과'},
    {flag: '🇰🇷', code: 'KR', currency: 'KRW', engName: 'South Korea', korName: '대한민국'},
    {flag: '🇩🇰', code: 'DK', currency: 'DKK', engName: 'Denmark', korName: '덴마크'},
    {flag: '🇩🇲', code: 'DM', currency: 'XCD', engName: 'Dominica', korName: '도미니카'},
    {flag: '🇨🇩', code: 'DO', currency: 'DOP', engName: 'Dominican Republic', korName: '도미니카 공화국'},
    {flag: '🇩🇪', code: 'DE', currency: 'EUR', engName: 'Germany', korName: '독일'},
    {flag: '🇹🇱', code: 'TL', currency: 'USD', engName: 'Timor-Leste', korName: '동티모르'},
    {flag: '🇱🇦', code: 'LA', currency: 'LAK', engName: 'Laos', korName: '라오스'},
    {flag: '🇱🇷', code: 'LR', currency: 'LRD', engName: 'Liberia', korName: '라이베리아'},
    {flag: '🇱🇻', code: 'LV', currency: 'EUR', engName: 'Latvia', korName: '라트비아'},
    {flag: '🇷🇺', code: 'RU', currency: 'RUB', engName: 'Russia', korName: '러시아'},
    {flag: '🇱🇧', code: 'LB', currency: 'LBP', engName: 'Lebanon', korName: '레바논'},
    {flag: '🇱🇸', code: 'LS', currency: 'LSL', engName: 'Lesotho', korName: '레소토'},
    {flag: '🇫🇷', code: 'RE', currency: 'EUR', engName: 'Reunion', korName: '레위니옹'},
    {flag: '🇷🇴', code: 'RO', currency: 'RON', engName: 'Romania', korName: '루마니아'},
    {flag: '🇱🇺', code: 'LU', currency: 'EUR', engName: 'Luxembourg', korName: '룩셈부르크'},
    {flag: '🇷🇼', code: 'RW', currency: 'RWF', engName: 'Rwanda', korName: '르완다'},
    {flag: '🇱🇾', code: 'LY', currency: 'LYD', engName: 'Libyan Arab Jamahiriya', korName: '리비아'},
    {flag: '🇱🇹', code: 'LT', currency: 'LTL', engName: 'Lithuania', korName: '리투아니아'},
    {flag: '🇱🇮', code: 'LI', currency: 'CHF', engName: 'Liechtenstein', korName: '리히텐슈타인'},
    {flag: '🇲🇬', code: 'MG', currency: 'MGA', engName: 'Madagascar', korName: '마다가스카르'},
    {flag: '🇲🇶', code: 'MQ', currency: 'EUR', engName: 'Martinique', korName: '마르티니크'},
    {flag: '🇲🇭', code: 'MH', currency: 'USD', engName: 'Marshall Islands', korName: '마셜 제도'},
    {flag: '🇾🇹', code: 'YT', currency: 'EUR', engName: 'Mayotte', korName: '마요트'},
    {flag: '🇲🇴', code: 'MO', currency: 'MOP', engName: 'Macao', korName: '마카오'},
    {flag: '🇲🇰', code: 'MK', currency: 'MKD', engName: 'Macedonia', korName: '마케도니아 공화국'},
    {flag: '🇲🇼', code: 'MW', currency: 'MWK', engName: 'Malawi', korName: '말라위'},
    {flag: '🇲🇾', code: 'MY', currency: 'MYR', engName: 'Malaysia', korName: '말레이시아'},
    {flag: '🇲🇱', code: 'ML', currency: 'XOF', engName: 'Mali', korName: '말리'},
    {flag: '🇮🇲', code: 'IM', currency: 'GBP', engName: 'Isle of Man', korName: '맨 섬'},
    {flag: '🇲🇽', code: 'MX', currency: 'MXN', engName: 'Mexico', korName: '멕시코'},
    {flag: '🇲🇨', code: 'MC', currency: 'EUR', engName: 'Monaco', korName: '모나코'},
    {flag: '🇲🇦', code: 'MA', currency: 'MAD', engName: 'Morocco', korName: '모로코'},
    {flag: '🇲🇺', code: 'MU', currency: 'MUR', engName: 'Mauritius', korName: '모리셔스'},
    {flag: '🇲🇷', code: 'MR', currency: 'MRO', engName: 'Mauritania', korName: '모리타니'},
    {flag: '🇲🇿', code: 'MZ', currency: 'MZN', engName: 'Mozambique', korName: '모잠비크'},
    {flag: '🇲🇪', code: 'ME', currency: 'EUR', engName: 'Montenegro', korName: '몬테네그로'},
    {flag: '🇲🇸', code: 'MS', currency: 'XCD', engName: 'Montserrat', korName: '몬트세랫'},
    {flag: '🇲🇩', code: 'MD', currency: 'MDL', engName: 'Moldova', korName: '몰도바'},
    {flag: '🇲🇻', code: 'MV', currency: 'MVR', engName: 'Maldives', korName: '몰디브'},
    {flag: '🇲🇹', code: 'MT', currency: 'EUR', engName: 'Malta', korName: '몰타'},
    {flag: '🇲🇳', code: 'MN', currency: 'MNT', engName: 'Mongolia', korName: '몽골'},
    {flag: '🇺🇸', code: 'US', currency: 'USD', engName: 'United States', korName: '미국'},
    {
        flag: '🇺🇸',
        code: 'UM',
        currency: 'USD',
        engName: 'United States Minor Outlying Islands',
        korName: '미국령 군소 제도',
    },
    {flag: '🇻🇮', code: 'VI', currency: 'USD', engName: 'Virgin Islands, U.S.', korName: '미국령 버진아일랜드'},
    {flag: '🇲🇲', code: 'MM', currency: 'MMK', engName: 'Myanmar', korName: '미얀마'},
    {flag: '🇫🇲', code: 'FM', currency: 'USD', engName: 'Micronesia', korName: '미크로네시아 연방'},
    {flag: '🇻🇺', code: 'VU', currency: 'VUV', engName: 'Vanuatu', korName: '바누아투'},
    {flag: '🇧🇸', code: 'BH', currency: 'BHD', engName: 'Bahrain', korName: '바레인'},
    {flag: '🇧🇧', code: 'BB', currency: 'BBD', engName: 'Barbados', korName: '바베이도스'},
    {flag: '🇻🇦', code: 'VA', currency: 'EUR', engName: 'Holy See', korName: '바티칸 시국'},
    {flag: '🇧🇸', code: 'BS', currency: 'BSD', engName: 'Bahamas', korName: '바하마'},
    {flag: '🇧🇩', code: 'BD', currency: 'BDT', engName: 'Bangladesh', korName: '방글라데시'},
    {flag: '🇧🇲', code: 'BM', currency: 'BMD', engName: 'Bermuda', korName: '버뮤다'},
    {flag: '🇧🇯', code: 'BJ', currency: 'XOF', engName: 'Benin', korName: '베냉'},
    {flag: '🇻🇪', code: 'VE', currency: 'VEF', engName: 'Venezuela', korName: '베네수엘라'},
    {flag: '🇻🇳', code: 'VN', currency: 'VND', engName: 'Vietnam', korName: '베트남'},
    {flag: '🇧🇪', code: 'BE', currency: 'EUR', engName: 'Belgium', korName: '벨기에'},
    {flag: '🇧🇾', code: 'BY', currency: 'BYR', engName: 'Belarus', korName: '벨라루스'},
    {flag: '🇧🇿', code: 'BZ', currency: 'BZD', engName: 'Belize', korName: '벨리즈'},
    {flag: '🇧🇦', code: 'BA', currency: 'BAM', engName: 'Bosnia and Herzegovina', korName: '보스니아 헤르체고비나'},
    {flag: '🇧🇼', code: 'BW', currency: 'BWP', engName: 'Botswana', korName: '보츠와나'},
    {flag: '🇧🇴', code: 'BO', currency: 'BOB', engName: 'Bolivia', korName: '볼리비아'},
    {flag: '🇧🇮', code: 'BI', currency: 'BIF', engName: 'Burundi', korName: '부룬디'},
    {flag: '🇧🇫', code: 'BF', currency: 'XOF', engName: 'Burkina Faso', korName: '부르키나파소'},
    {flag: '🏳', code: 'BV', currency: 'NOK', engName: 'Bouvet Island', korName: '부베 섬'},
    {flag: '🇧🇹', code: 'BT', currency: 'BTN', engName: 'Bhutan', korName: '부탄'},
    {flag: '🏳', code: 'MP', currency: 'USD', engName: 'Northern Mariana Islands', korName: '북마리아나 제도'},
    {flag: '🇧🇬', code: 'BG', currency: 'BGN', engName: 'Bulgaria', korName: '불가리아'},
    {flag: '🇧🇷', code: 'BR', currency: 'BRL', engName: 'Brazil', korName: '브라질'},
    {flag: '🇧🇳', code: 'BN', currency: 'BND', engName: 'Brunei Darussalam', korName: '브루나이'},
    {flag: '🇼🇸', code: 'WS', currency: 'WST', engName: 'Samoa', korName: '사모아'},
    {flag: '🇸🇦', code: 'SA', currency: 'SAR', engName: 'Saudi Arabia', korName: '사우디아라비아'},
    {flag: '🇬🇸', code: 'GS', currency: 'GBP', engName: 'South Georgia', korName: '사우스조지아 사우스샌드위치 제도'},
    {flag: '🇸🇲', code: 'SM', currency: 'EUR', engName: 'San Marino', korName: '산마리노'},
    {flag: '🇸🇹', code: 'ST', currency: 'STD', engName: 'Sao Tome and Principe', korName: '상투메 프린시페'},
    {flag: '🇵🇲', code: 'PM', currency: 'EUR', engName: 'Saint Pierre and Miquelon', korName: '생피에르 미클롱'},
    {flag: '🇪🇭', code: 'EH', currency: 'MAD', engName: 'Western Sahara', korName: '서사하라'},
    {flag: '🇸🇳', code: 'SN', currency: 'XOF', engName: 'Senegal', korName: '세네갈'},
    {flag: '🇷🇸', code: 'RS', currency: 'RSD', engName: 'Serbia', korName: '세르비아'},
    {flag: '🇸🇨', code: 'SC', currency: 'SCR', engName: 'Seychelles', korName: '세이셸'},
    {flag: '🇱🇨', code: 'LC', currency: 'XCD', engName: 'Saint Lucia', korName: '세인트루시아'},
    {
        flag: '🇻🇨',
        code: 'VC',
        currency: 'XCD',
        engName: 'Saint Vincent and the Grenadines',
        korName: '세인트빈센트 그레나딘',
    },
    {flag: '🇰🇳', code: 'KN', currency: 'XCD', engName: 'Saint Kitts and Nevis', korName: '세인트키츠 네비스'},
    {flag: '🇸🇭', code: 'SH', currency: 'SHP', engName: 'Saint Helena', korName: '세인트헬레나'},
    {flag: '🇸🇴', code: 'SO', currency: 'SOS', engName: 'Somalia', korName: '소말리아'},
    {flag: '🇸🇧', code: 'SB', currency: 'SBD', engName: 'Solomon Islands', korName: '솔로몬 제도'},
    {flag: '🇸🇩', code: 'SD', currency: 'SDG', engName: 'Sudan', korName: '수단'},
    {flag: '🇸🇷', code: 'SR', currency: 'SRD', engName: 'Suriname', korName: '수리남'},
    {flag: '🇱🇰', code: 'LK', currency: 'LKR', engName: 'Sri Lanka', korName: '스리랑카'},
    {flag: '🇩🇰', code: 'SJ', currency: 'NOK', engName: 'Svalbard and Jan Mayen', korName: '스발바르 얀마옌'},
    {flag: '🇸🇿', code: 'SZ', currency: 'SZL', engName: 'Swaziland', korName: '스와질란드'},
    {flag: '🇸🇪', code: 'SE', currency: 'SEK', engName: 'Sweden', korName: '스웨덴'},
    {flag: '🇨🇭', code: 'CH', currency: 'CHF', engName: 'Switzerland', korName: '스위스'},
    {flag: '🇪🇸', code: 'ES', currency: 'EUR', engName: 'Spain', korName: '스페인'},
    {flag: '🇸🇰', code: 'SK', currency: 'EUR', engName: 'Slovakia', korName: '슬로바키아'},
    {flag: '🇸🇮', code: 'SI', currency: 'EUR', engName: 'Slovenia', korName: '슬로베니아'},
    {flag: '🇸🇾', code: 'SY', currency: 'SYP', engName: 'Syrian Arab Republic', korName: '시리아'},
    {flag: '🇸🇱', code: 'SL', currency: 'SLL', engName: 'Sierra Leone', korName: '시에라리온'},
    {flag: '🇸🇬', code: 'SG', currency: 'SGD', engName: 'Singapore', korName: '싱가포르'},
    {flag: '🇦🇪', code: 'AE', currency: 'AED', engName: 'United Arab Emirates', korName: '아랍에미리트'},
    {flag: '🇦🇼', code: 'AW', currency: 'AWG', engName: 'Aruba', korName: '아루바'},
    {flag: '🇦🇲', code: 'AM', currency: 'AMD', engName: 'Armenia', korName: '아르메니아'},
    {flag: '🇦🇷', code: 'AR', currency: 'ARS', engName: 'Argentina', korName: '아르헨티나'},
    {flag: '🇺🇸', code: 'AS', currency: 'USD', engName: 'American Samoa', korName: '아메리칸사모아'},
    {flag: '🇮🇸', code: 'IS', currency: 'ISK', engName: 'Iceland', korName: '아이슬란드'},
    {flag: '🇭🇹', code: 'HT', currency: 'HTG', engName: 'Haiti', korName: '아이티'},
    {flag: '🇮🇪', code: 'IE', currency: 'EUR', engName: 'Ireland', korName: '아일랜드'},
    {flag: '🇦🇿', code: 'AZ', currency: 'AZN', engName: 'Azerbaijan', korName: '아제르바이잔'},
    {flag: '🇦🇫', code: 'AF', currency: 'AFN', engName: 'Afghanistan', korName: '아프가니스탄'},
    {flag: '🇦🇩', code: 'AD', currency: 'EUR', engName: 'Andorra', korName: '안도라'},
    {flag: '🇦🇱', code: 'AL', currency: 'ALL', engName: 'Albania', korName: '알바니아'},
    {flag: '🇩🇿', code: 'DZ', currency: 'DZD', engName: 'Algeria', korName: '알제리'},
    {flag: '🇦🇴', code: 'AO', currency: 'AOA', engName: 'Angola', korName: '앙골라'},
    {flag: '🇦🇬', code: 'AG', currency: 'XCD', engName: 'Antigua and Barbuda', korName: '앤티가 바부다'},
    {flag: '🇦🇮', code: 'AI', currency: 'XCD', engName: 'Anguilla', korName: '앵귈라'},
    {flag: '🇪🇷', code: 'ER', currency: 'ERN', engName: 'Eritrea', korName: '에리트레아'},
    {flag: '🇪🇪', code: 'EE', currency: 'EUR', engName: 'Estonia', korName: '에스토니아'},
    {flag: '🇪🇨', code: 'EC', currency: 'USD', engName: 'Ecuador', korName: '에콰도르'},
    {flag: '🇪🇹', code: 'ET', currency: 'ETB', engName: 'Ethiopia', korName: '에티오피아'},
    {flag: '🇸🇻', code: 'SV', currency: 'USD', engName: 'El Salvador', korName: '엘살바도르'},
    {flag: '🇬🇧', code: 'GB', currency: 'GBP', engName: 'United Kingdom', korName: '영국'},
    {flag: '🇻🇬', code: 'VG', currency: 'USD', engName: 'Virgin Islands, British', korName: '영국령 버진아일랜드'},
    {flag: '🇮🇴', code: 'IO', currency: 'USD', engName: 'British Indian Ocean Territory', korName: '영국령 인도양 지역'},
    {flag: '🇾🇪', code: 'YE', currency: 'YER', engName: 'Yemen', korName: '예멘'},
    {flag: '🇴🇲', code: 'OM', currency: 'OMR', engName: 'Oman', korName: '오만'},
    {flag: '🇦🇺', code: 'AU', currency: 'AUD', engName: 'Australia', korName: '오스트레일리아'},
    {flag: '🇦🇹', code: 'AT', currency: 'EUR', engName: 'Austria', korName: '오스트리아'},
    {flag: '🇭🇳', code: 'HN', currency: 'HNL', engName: 'Honduras', korName: '온두라스'},
    {flag: '🇦🇽', code: 'AX', currency: 'EUR', engName: 'Åland Islands', korName: '올란드 제도'},
    {flag: '🇯🇴', code: 'JO', currency: 'JOD', engName: 'Jordan', korName: '요르단'},
    {flag: '🇺🇬', code: 'UG', currency: 'UGX', engName: 'Uganda', korName: '우간다'},
    {flag: '🇺🇾', code: 'UY', currency: 'UYU', engName: 'Uruguay', korName: '우루과이'},
    {flag: '🇺🇿', code: 'UZ', currency: 'UZS', engName: 'Uzbekistan', korName: '우즈베키스탄'},
    {flag: '🇺🇦', code: 'UA', currency: 'UAH', engName: 'Ukraine', korName: '우크라이나'},
    {flag: '🇼🇫', code: 'WF', currency: 'XPF', engName: 'Wallis and Futuna', korName: '왈리스 퓌튀나'},
    {flag: '🇮🇶', code: 'IQ', currency: 'IQD', engName: 'Iraq', korName: '이라크'},
    {flag: '🇮🇷', code: 'IR', currency: 'IRR', engName: 'Iran', korName: '이란'},
    {flag: '🇮🇱', code: 'IL', currency: 'ILS', engName: 'Israel', korName: '이스라엘'},
    {flag: '🇪🇬', code: 'EG', currency: 'EGP', engName: 'Egypt', korName: '이집트'},
    {flag: '🇮🇹', code: 'IT', currency: 'EUR', engName: 'Italy', korName: '이탈리아'},
    {flag: '🇮🇩', code: 'ID', currency: 'IDR', engName: 'Indonesia', korName: '인도네시아'},
    {flag: '🇮🇳', code: 'IN', currency: 'INR', engName: 'India', korName: '인도'},
    {flag: '🇯🇵', code: 'JP', currency: 'JPY', engName: 'Japan', korName: '일본'},
    {flag: '🇯🇲', code: 'JM', currency: 'JMD', engName: 'Jamaica', korName: '자메이카'},
    {flag: '🇿🇲', code: 'ZM', currency: 'ZMK', engName: 'Zambia', korName: '잠비아'},
    {flag: '🇯🇪', code: 'JE', currency: 'GBP', engName: 'Jersey', korName: '저지 섬'},
    {flag: '🇬🇶', code: 'GQ', currency: 'XAF', engName: 'Equatorial Guinea', korName: '적도 기니'},
    {flag: '🇰🇵', code: 'KP', currency: 'KPW', engName: 'North Korea', korName: '조선민주주의인민공화국'},
    {flag: '🇨🇫', code: 'CF', currency: 'XAF', engName: 'Central African Republic', korName: '중앙아프리카 공화국'},
    {flag: '🇹🇼', code: 'TW', currency: 'TWD', engName: 'Taiwan', korName: '중화민국'},
    {flag: '🇨🇳', code: 'CN', currency: 'CNY', engName: 'China', korName: '중화인민공화국'},
    {flag: '🇩🇯', code: 'DJ', currency: 'DJF', engName: 'Djibouti', korName: '지부티'},
    {flag: '🇬🇮', code: 'GI', currency: 'GIP', engName: 'Gibraltar', korName: '지브롤터'},
    {flag: '🇿🇼', code: 'ZW', currency: 'ZWL', engName: 'Zimbabwe', korName: '짐바브웨'},
    {flag: '🇹🇩', code: 'TD', currency: 'XAF', engName: 'Chad', korName: '차드'},
    {flag: '🇨🇿', code: 'CZ', currency: 'CZK', engName: 'Czech Republic', korName: '체코'},
    {flag: '🇨🇱', code: 'CL', currency: 'CLP', engName: 'Chile', korName: '칠레'},
    {flag: '🇨🇲', code: 'CM', currency: 'XAF', engName: 'Cameroon', korName: '카메룬'},
    {flag: '🇨🇻', code: 'CV', currency: 'CVE', engName: 'Cape Verde', korName: '카보베르데'},
    {flag: '🇰🇿', code: 'KZ', currency: 'KZT', engName: 'Kazakhstan', korName: '카자흐스탄'},
    {flag: '🇶🇦', code: 'QA', currency: 'QAR', engName: 'Qatar', korName: '카타르'},
    {flag: '🇰🇭', code: 'KH', currency: 'KHR', engName: 'Cambodia', korName: '캄보디아'},
    {flag: '🇨🇦', code: 'CA', currency: 'CAD', engName: 'Canada', korName: '캐나다'},
    {flag: '🇰🇪', code: 'KE', currency: 'KES', engName: 'Kenya', korName: '케냐'},
    {flag: '🇰🇾', code: 'KY', currency: 'KYD', engName: 'Cayman Islands', korName: '케이맨 제도'},
    {flag: '🇰🇲', code: 'KM', currency: 'KMF', engName: 'Comoros', korName: '코모로'},
    {flag: '🇨🇷', code: 'CR', currency: 'CRC', engName: 'Costa Rica', korName: '코스타리카'},
    {flag: '🇨🇨', code: 'CC', currency: 'AUD', engName: 'Cocos (Keeling) Islands', korName: '코코스 제도'},
    {flag: '🇨🇮', code: 'CI', currency: 'XOF', engName: "Cote d'Ivoire", korName: '코트디부아르'},
    {flag: '🇨🇴', code: 'CO', currency: 'COP', engName: 'Colombia', korName: '콜롬비아'},
    {flag: '🇨🇬', code: 'CG', currency: 'XAF', engName: 'Congo', korName: '콩고 공화국'},
    {
        flag: '🇨🇩',
        code: 'CD',
        currency: 'CDF',
        engName: 'Congo, The Democratic Republic of the Congo',
        korName: '콩고 민주 공화국',
    },
    {flag: '🇨🇺', code: 'CU', currency: 'CUP', engName: 'Cuba', korName: '쿠바'},
    {flag: '🇰🇼', code: 'KW', currency: 'KWD', engName: 'Kuwait', korName: '쿠웨이트'},
    {flag: '🇨🇰', code: 'CK', currency: 'NZD', engName: 'Cook Islands', korName: '쿡 제도'},
    {flag: '🇭🇷', code: 'HR', currency: 'HRK', engName: 'Croatia', korName: '크로아티아'},
    {flag: '🇨🇽', code: 'CX', currency: 'AUD', engName: 'Christmas Island', korName: '크리스마스 섬'},
    {flag: '🇰🇬', code: 'KG', currency: 'KGS', engName: 'Kyrgyzstan', korName: '키르기스스탄'},
    {flag: '🇰🇮', code: 'KI', currency: 'AUD', engName: 'Kiribati', korName: '키리바시'},
    {flag: '🇨🇾', code: 'CY', currency: 'EUR', engName: 'Cyprus', korName: '키프로스'},
    {flag: '🇹🇭', code: 'TH', currency: 'THB', engName: 'Thailand', korName: '타이'},
    {flag: '🇹🇯', code: 'TJ', currency: 'TJS', engName: 'Tajikistan', korName: '타지키스탄'},
    {flag: '🇹🇿', code: 'TZ', currency: 'TZS', engName: 'Tanzania', korName: '탄자니아'},
    {flag: '🇹🇨', code: 'TC', currency: 'USD', engName: 'Turks and Caicos Islands', korName: '터크스 케이커스 제도'},
    {flag: '🇹🇷', code: 'TR', currency: 'TRY', engName: 'Turkey', korName: '터키'},
    {flag: '🇹🇬', code: 'TG', currency: 'XOF', engName: 'Togo', korName: '토고'},
    {flag: '🇹🇰', code: 'TK', currency: 'NZD', engName: 'Tokelau', korName: '토켈라우'},
    {flag: '🇹🇴', code: 'TO', currency: 'TOP', engName: 'Tonga', korName: '통가'},
    {flag: '🇹🇲', code: 'TM', currency: 'TMT', engName: 'Turkmenistan', korName: '투르크메니스탄'},
    {flag: '🇹🇻', code: 'TV', currency: 'AUD', engName: 'Tuvalu', korName: '투발루'},
    {flag: '🇹🇳', code: 'TN', currency: 'TND', engName: 'Tunisia', korName: '튀니지'},
    {flag: '🇹🇹', code: 'TT', currency: 'TTD', engName: 'Trinidad and Tobago', korName: '트리니다드 토바고'},
    {flag: '🇵🇦', code: 'PA', currency: 'PAB', engName: 'Panama', korName: '파나마'},
    {flag: '🇵🇾', code: 'PY', currency: 'PYG', engName: 'Paraguay', korName: '파라과이'},
    {flag: '🇵🇰', code: 'PK', currency: 'PKR', engName: 'Pakistan', korName: '파키스탄'},
    {flag: '🇵🇬', code: 'PG', currency: 'PGK', engName: 'Papua New Guinea', korName: '파푸아 뉴기니'},
    {flag: '🇵🇼', code: 'PW', currency: 'USD', engName: 'Palau', korName: '팔라우'},
    {flag: '🇵🇸', code: 'PS', currency: 'ILS', engName: 'Palestinian Territory', korName: '팔레스타인'},
    {flag: '🇫🇴', code: 'FO', currency: 'DKK', engName: 'Faroe Islands', korName: '페로 제도'},
    {flag: '🇵🇪', code: 'PE', currency: 'PEN', engName: 'Peru', korName: '페루'},
    {flag: '🇵🇹', code: 'PT', currency: 'EUR', engName: 'Portugal', korName: '포르투갈'},
    {flag: '🇫🇰', code: 'FK', currency: 'FKP', engName: 'Falkland Islands', korName: '포클랜드 제도'},
    {flag: '🇵🇱', code: 'PL', currency: 'PLN', engName: 'Poland', korName: '폴란드'},
    {flag: '🇵🇷', code: 'PR', currency: 'USD', engName: 'Puerto Rico', korName: '푸에르토리코'},
    {flag: '🇫🇷', code: 'FR', currency: 'EUR', engName: 'France', korName: '프랑스'},
    {
        flag: '🇹🇫',
        code: 'TF',
        currency: 'EUR',
        engName: 'French Southern Territories',
        korName: '프랑스령 남부와 남극 지역',
    },
    {flag: '🇵🇫', code: 'PF', currency: 'XPF', engName: 'French Polynesia', korName: '프랑스령 폴리네시아'},
    {flag: '🇫🇯', code: 'FJ', currency: 'FJD', engName: 'Fiji', korName: '피지'},
    {flag: '🇫🇮', code: 'FI', currency: 'EUR', engName: 'Finland', korName: '핀란드'},
    {flag: '🇵🇭', code: 'PH', currency: 'PHP', engName: 'Philippines', korName: '필리핀'},
    {flag: '🇵🇳', code: 'PN', currency: 'NZD', engName: 'Pitcairn', korName: '핏케언 제도'},
    {
        flag: '🏳',
        code: 'HM',
        currency: 'AUD',
        engName: 'Heard Island and Mcdonald Islands',
        korName: '허드 맥도널드 제도',
    },
    {flag: '🇭🇺', code: 'HU', currency: 'HUF', engName: 'Hungary', korName: '헝가리'},
    {flag: '🇭🇰', code: 'HK', currency: 'HKD', engName: 'Hong Kong', korName: '홍콩'},
];

export default countries;
